
DELIMITER &&  
CREATE PROCEDURE `CUSTOMER_NAME_LIVING_IN_CITY`(IN `CITY` VARCHAR(40))

BEGIN  
    SELECT CUST_NAME FROM customer WHERE WORKING_AREA = CITY;    
END &&  
DELIMITER ; 

Call `CUSTOMER_NAME_LIVING_IN_CITY`("Bangalore");