SELECT D.Dnumber, D.Dname, COUNT(*) FROM DEPARTMENT D, DEPT_LOCATIONS DE WHERE D.Dnumber=DE.Dnumber AND D.Mgr_ssn IN (SELECT Essn FROM DEPENDENT WHERE
Sex="F" GROUP BY ESSN HAVING COUNT(*)>1) GROUP BY D.Dnumber, D.Dname;
